# Maps a collection of pods to a single IP address
# Accessible via env variables, or with a DNS addon
kind: Service
apiVersion: v1

metadata:
  name: rest-api

spec:
  # Select pods in the postgress app
  selector:
    app: rest-api

  # Which port data is received on.
  # By default, targetPort == port, so data will be forwarded to port 5432 of selected pods.
  ports:
    - port: 5000
