apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "linkr"
  namespace: "default"
  labels:
    app: "linkr"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "linkr"
  template:
    metadata:
      labels:
        app: "linkr"
    spec:
      containers:
        - name: "linkr"
          image: "gcr.io/linkr-software/linkr"


---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "linkr-service"
  namespace: "default"
  labels:
    app: "linkr"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  selector:
    app: "linkr"
  type: "LoadBalancer"
  loadBalancerIP: ""

---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  namespace: "default"
  labels:
    app: "postgres"
data:
  POSTGRES_DB: "linkr"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"


---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgres"
  namespace: "default"
  labels:
    app: "postgres"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
        - name: "postgres"
          image: "postgres:9.6.2"
          env:
            - name: "POSTGRES_DB"
              valueFrom:
                configMapKeyRef:
                  key: "POSTGRES_DB"
                  name: "postgres-config"
            - name: "POSTGRES_USER"
              valueFrom:
                configMapKeyRef:
                  key: "POSTGRES_USER"
                  name: "postgres-config"
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                configMapKeyRef:
                  key: "POSTGRES_PASSWORD"
                  name: "postgres-config"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/db-data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres