# Maps a collection of pods to a single IP address
# Accessible via env variables, or with a DNS addon
kind: Service
apiVersion: v1

metadata:
  name: postgres

spec:
  # Select pods in the postgress app
  selector:
    app: postgres

  # Which port data is received on.
  # By default, targetPort == port
  ports:
    - port: {{ .Values.postgres.port }}
