# Create a persistent volume for the database
apiVersion: v1
kind: PersistentVolume

metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgres

spec:
  # manual means no automatic deleting of data
  storageClassName: manual

  capacity:
    storage: {{ .Values.postgres.storage.capacity }}

  accessModes:
    - ReadWriteMany

  # The volume is at /mnt/postgres-data on cluster's Node (i.e. your computer)
  # In production, you wouldn't use hostPath but something else
  hostPath:
    path: {{ .Values.postgres.storage.datapath }}

