{{- if not .Values.deployToGcp }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkr-ingress
spec:
  tls:
  - hosts:
    - {{ .Values.http.hostname }}
    secretName: {{ .Values.http.tls_secret_name }}
  rules:
    - host: {{ .Values.http.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.frontend.port }}
{{- end }}
