apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guest
  namespace: default
subjects:
- kind: Group
  name: guest
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: guest