apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-pv
    labels:
        type: local
spec:
    # manual: data retained, must be reclaimed manually
    storageClassName: manual

    capacity:
        storage: 10Mi

    # ReadWriteMany means volume can be mounted as read-write by multiple nodes
    accessModes:
        - ReadWriteMany

    # The volume is at /mnt/postgres-data on cluster's Node
    hostPath:
        path: "/mnt/postgres-data"

