apiVersion: v1
kind: PersistentVolume

metadata:
  name: postgres-pv
  labels:
    type: local

spec:
  # manual: data retained, must be reclaimed manually
  storageClassName: manual

  capacity:
    storage: 10Mi

  # ReadWriteOnce means volume can be mounted as read-write by single Node
  accessModes:
    - ReadWriteOnce

  # The volume is at /mnt/postgres-data on cluster's Node (i.e. your computer)
  # In production, you wouldn't use hostPath but something else
  hostPath:
    path: "/mnt/postgres-data"

