apiVersion: v1
kind: ConfigMap

metadata:
  name: postgres-config
  labels:
    app: postgres

# TODO: this should be in a Secrets object eventually
data:
  POSTGRES_DB: db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
