apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pvclaim
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 10Mi
