apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  # The selector is how the deployment finds which pods to manage (should be the same as the template)
  selector:
    matchLabels:
      app: postgres

  minReadySeconds: 5

  # Template used to create new pods
  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-config

          # Mount at standard postgres path
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb

          # Which ports to expose on
          ports:
            - containerPort: 5432

      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pvclaim
