# Create a persistent volume for the database
apiVersion: v1
kind: PersistentVolume

metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres

spec:
  # manual means no automatic deleting of data
  storageClassName: manual

  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteMany

  # The volume is at /opt/postgres/data on cluster's Node (i.e. your computer)
  # In production, you wouldn't use hostPath but something else
  hostPath:
    path: "/opt/postgres/data"

